# Generated by Django 3.2.4 on 2021-08-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
