# Generated by Django 3.2.4 on 2021-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0003_pictureupgrade_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupgrade',
            name='answers',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='size',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='state',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='x',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='y',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
