# Generated by Django 3.2.4 on 2021-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0007_alter_pictureupgrade_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='picpart'),
        ),
    ]
