# Generated by Django 3.2.4 on 2021-07-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0009_pictureupgrade_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureupgrade',
            name='color_limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pictureupgrade',
            name='size_part',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='pictureupgrade',
            name='width',
            field=models.PositiveSmallIntegerField(default=800),
        ),
    ]
