# Generated by Django 3.2.4 on 2021-07-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0010_auto_20210705_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureupgrade',
            name='hard',
            field=models.PositiveSmallIntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='color_limit',
            field=models.PositiveSmallIntegerField(default=120),
        ),
    ]
