# Generated by Django 3.2.4 on 2021-07-27 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0011_auto_20210727_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupgrade',
            name='hard',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
