# Generated by Django 3.2.4 on 2021-08-01 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0012_alter_pictureupgrade_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureupgrade',
            name='favorite',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='color_limit',
            field=models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='width',
            field=models.PositiveSmallIntegerField(default=800, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(100)]),
        ),
    ]
