# Generated by Django 3.2.4 on 2021-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0013_auto_20210801_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupgrade',
            name='favorite',
            field=models.BooleanField(default=0),
        ),
    ]
