# Generated by Django 3.2.4 on 2021-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('tune', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PictureUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matrix', models.CharField(max_length=100)),
                ('tune', models.CharField(max_length=100)),
            ],
        ),
    ]
