"""empty message

Revision ID: 4690fe55ea2b
Revises: 33f38becd55e
Create Date: 2021-06-14 23:28:24.059791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4690fe55ea2b'
down_revision = '33f38becd55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'product', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
