# Generated by Django 3.2.4 on 2021-06-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picpart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='description',
        ),
        migrations.AddField(
            model_name='pictures',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictures',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pictureupgrade',
            name='picture',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='picpart.pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='matrix',
            field=models.JSONField(unique=True),
        ),
        migrations.AlterField(
            model_name='pictureupgrade',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picpart.pictures')),
            ],
        ),
    ]
