# Generated by Django 3.2.4 on 2021-06-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0002_auto_20210626_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
    ]
