# Generated by Django 3.2.4 on 2021-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0006_alter_pictureupgrade_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureupgrade',
            name='matrix',
            field=models.JSONField(default=dict),
        ),
    ]
