# Generated by Django 3.2.4 on 2021-07-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpart', '0008_pictures_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureupgrade',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='process'),
        ),
    ]
