version: "3"

services:
  web-app:
    build:
      context: ./web-app
      dockerfile: ./Dockerfile
#    command: flask run --port=3000
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@postgres:5432/app
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5416:5432
